export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ROUND_NOT_WAITING: 'ROUND_NOT_WAITING',
  ROUND_NOT_RUNNING: 'ROUND_NOT_RUNNING',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  BET_ALREADY_EXISTS: 'BET_ALREADY_EXISTS',
  BET_NOT_FOUND: 'BET_NOT_FOUND',
  BET_ALREADY_RESOLVED: 'BET_ALREADY_RESOLVED',
  INVALID_AUTO_CASHOUT: 'INVALID_AUTO_CASHOUT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
