export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  INVALID_LAUNCH_TOKEN: 'INVALID_LAUNCH_TOKEN',
  LAUNCH_TOKEN_EXPIRED: 'LAUNCH_TOKEN_EXPIRED',
  LAUNCH_TOKEN_ALREADY_USED: 'LAUNCH_TOKEN_ALREADY_USED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  DUPLICATE_TRANSACTION: 'DUPLICATE_TRANSACTION',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
